Repository sparkfabrik/terraform-google-gcp-cloud-native-drupal-resources, pull requests merged in 2024-11, with the labels that each got.

#32 add kubernetes namespace labels
  CHANGELOG.md
  README.md
  main.tf
  variables.tf
Labels: Review effort [1-5]: 2

#35 refs #000: add default label to namespace resources
  .gitignore
  CHANGELOG.md
  README.md
  main.tf
  secrets.tf
  variables.tf
Labels: Review effort [1-5]: 2

#36 feat: change CloudSQL dump bucket lifecycle rules
  CHANGELOG.md
  README.md
  cloudsql_dumps_bucket.tf
Labels: Review effort [1-5]: 2

#38 refs platform/3259: update bucket creation modules
  CHANGELOG.md
  main.tf
Labels: Review effort [1-5]: 2

#39 feat: upgrade terraform docs using renovate
  CHANGELOG.md
  Makefile
  renovate.json
Labels: Review effort [1-5]: 2

#41 fix: update readme
  README.md
Labels: Review effort [1-5]: 1

#43 refs platform/3259: update bucket helper module version
  CHANGELOG.md
  main.tf
Labels: Review effort [1-5]: 1

#44 3259 remove bucket soft delete
  CHANGELOG.md
  README.md
  variables.tf
Labels: Review effort [1-5]: 1

#45 3237 enhance output of module terraform google gcp cloud native drupal resources
  README.md
  outputs.tf
Labels: Review effort [1-5]: 3, Possible security concern

#46 3237 changelog
  CHANGELOG.md
Labels: Review effort [1-5]: 1
